// Produces the three archives a release needs:
//
//   dist/melonspeak-chrome-<version>.zip    → Chrome Web Store
//   dist/melonspeak-firefox-<version>.zip   → addons.mozilla.org
//   dist/melonspeak-source-<version>.zip    → AMO "source code" upload
//
// The source archive is not optional. AMO requires the original sources
// whenever the submitted files are generated by a build step that obscures
// them, and esbuild minifies every bundle in a production build. An add-on
// submitted without it is rejected during review, not at upload.
//
// Run via `npm run package`, which builds first.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, statSync } from 'node:fs';
import { isAbsolute, join, resolve } from 'node:path';

const { version } = JSON.parse(readFileSync('package.json', 'utf8'));
const OUT = 'dist';

/** Files that must exist in a built target before it is worth zipping. */
const REQUIRED = [
  'manifest.json',
  'background.js',
  'reader/reader.html',
  'reader/reader.js',
  'onboarding/onboarding.html',
  'player/engine-worker.js',
  'icons/icon128.png',
  'wasm/ort/ort-wasm-simd-threaded.jsep.wasm',
  'wasm/tjs/ort-wasm-simd-threaded.jsep.wasm',
  'wasm/piper/piper_phonemize.wasm',
];

/** What the source archive carries. Everything needed to reproduce a build,
 *  and nothing that would make a reviewer download 300 MB of node_modules. */
const SOURCE_PATHS = [
  'src',
  'scripts',
  'docs',
  'package.json',
  'package-lock.json',
  'tsconfig.json',
  'README.md',
  'LICENSE',
  'PRIVACY.md',
  'CHANGELOG.md',
];

function fail(msg) {
  console.error(`package: ${msg}`);
  process.exit(1);
}

/**
 * Zips `paths` (interpreted relative to `cwd`) into `archive`.
 *
 * `archive` must be absolute. `zip` updates an existing archive in place
 * rather than replacing it, so a stale one must be deleted first — and a
 * relative path would not survive the cwd change, leaving the delete pointing
 * somewhere else while zip happily merged the new build into the old archive.
 * That shipped dead, differently-hashed chunks from every previous build.
 *
 * -X drops extra attributes and timestamps, so the same tree zips identically.
 */
function zip(archive, paths, cwd) {
  if (!isAbsolute(archive)) throw new Error(`zip(): archive path must be absolute: ${archive}`);
  rmSync(archive, { force: true });
  execFileSync('zip', ['-qrX', archive, ...paths, '-x', '.DS_Store', '-x', '*/.DS_Store'], {
    cwd,
    stdio: ['ignore', 'inherit', 'inherit'],
  });
}

function mb(path) {
  return `${(statSync(path).size / 1_000_000).toFixed(1)} MB`;
}

function packageTarget(browser) {
  const dir = join(OUT, browser);
  if (!existsSync(dir)) fail(`${dir} does not exist — run \`npm run build\` first.`);

  for (const file of REQUIRED) {
    if (!existsSync(join(dir, file))) fail(`${dir}/${file} is missing from the build.`);
  }

  // A version mismatch here means a store rejects the upload for "version did
  // not increase" long after this script reported success.
  const manifest = JSON.parse(readFileSync(join(dir, 'manifest.json'), 'utf8'));
  if (manifest.version !== version) {
    fail(`${dir}/manifest.json is version ${manifest.version}, package.json is ${version}.`);
  }

  // Store-blocking manifest requirements, asserted on the artifact that is
  // actually uploaded rather than on the source manifest.
  if (browser === 'firefox') {
    const gecko = manifest.browser_specific_settings?.gecko;
    if (!gecko?.data_collection_permissions?.required?.length) {
      fail(
        'firefox manifest is missing browser_specific_settings.gecko.data_collection_permissions — ' +
          'AMO rejects new submissions without it.',
      );
    }
  }

  const archive = `melonspeak-${browser}-${version}.zip`;
  const full = resolve(OUT, archive);
  // Zip from inside the build directory: both stores require the manifest at
  // the archive root, not nested under dist/<browser>/.
  zip(full, ['.'], dir);
  console.log(`  ${archive.padEnd(36)} ${mb(full)}`);
  return full;
}

function packageSource() {
  const present = SOURCE_PATHS.filter((p) => existsSync(p));
  const missing = SOURCE_PATHS.filter((p) => !existsSync(p));
  if (missing.length > 0) {
    console.warn(`  note: not in source archive (absent): ${missing.join(', ')}`);
  }
  const archive = `melonspeak-source-${version}.zip`;
  const full = resolve(OUT, archive);
  zip(full, present, '.');
  console.log(`  ${archive.padEnd(36)} ${mb(full)}`);
  return full;
}

mkdirSync(OUT, { recursive: true });
console.log(`packaging MelonSpeak ${version}\n`);
packageTarget('chrome');
packageTarget('firefox');
packageSource();
console.log(`\nStore limits: Chrome Web Store 2 GB, addons.mozilla.org 200 MB — all well under.`);
console.log(`Next: docs/store/DEPLOY.md`);
